# Generated by Django 2.2.7 on 2020-03-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='Usuario',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='book',
            name='total_copies',
            field=models.IntegerField(),
        ),
    ]
